name: Bilibili Video Crawler

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 支持手动触发

env:
  UP_UID: "3546719115545125"  # 这里填写UP主的UID
  UP_NAME: "Double咕Gu"    # 这里填写UP主的名称

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run crawler
      run: python scripts/bilibili_crawler.py
      env:
        UP_UID: ${{ env.UP_UID }}
        UP_NAME: ${{ env.UP_NAME }}
        
    - name: Config Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
    - name: Commit and Push
      run: |
        git checkout data || git checkout -b data
        git add data/
        git commit -m "更新视频数据 $(date '+%Y-%m-%d %H:%M:%S')" || exit 0
        git push origin data 